name: rawg_flutter
description: A Flutter Project that seeks to provide a front face to the RAWG Game Platform

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.0
  chopper: ^4.0.5
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  freezed: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.5.0
  logging: ^1.0.2
  progressive_image: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.10
  chopper_generator: ^4.0.5
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_alt.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#000000"
  image: "assets/app_alt.png"
  android_12:
    icon_background_color: "#000000"
    image: "assets/app_alt.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
